version: '3.7'

# Settings and configurations that are common for all containers
x-minio-common: &minio-common
  image: quay.io/minio/minio:RELEASE.2022-11-17T23-20-09Z
  command: server --console-address ":9001" http://minio{1...3}/data{1...5}
  expose:
    - "9000"
    - "9001"
  environment:
    - MINIO_ROOT_USER=admin
    - MINIO_ROOT_PASSWORD=admin
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3

# starts 4 docker containers running minio server instances.
# using nginx reverse proxy, load balancing, you can access
# it through port 9000.
services:
  minio1:
    <<: *minio-common
    hostname: minio1
    volumes:
      - /mnt/disk1/lost+found/data1-1:/data1
      - /mnt/disk2/lost+found/data1-2:/data2
      - /mnt/disk3/lost+found/data1-3:/data3

  minio2:
    <<: *minio-common
    hostname: minio2
    volumes:
      - /mnt/disk1/lost+found/data2-1:/data1
      - /mnt/disk2/lost+found/data2-2:/data2
      - /mnt/disk3/lost+found/data2-3:/data3

  minio3:
    <<: *minio-common
    hostname: minio3
    volumes:
      - /mnt/disk1/lost+found/data3-1:/data1
      - /mnt/disk2/lost+found/data3-2:/data2
      - /mnt/disk3/lost+found/data3-3:/data3

  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx

    volumes:
      - ./log:/var/log/nginx
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./sata.sys/:/etc/nginx/ssl/
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - minio1
      - minio2
      - minio3
